services:
  - type: web
    name: calculadora-notas
    env: python
    region: oregon
    plan: free
    repo: <your-git-repo-url>
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
